language: java

jdk:
  - openjdk8

branches:
  only:
    - master


scripts: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


notifications:
  email:
    recipients:
      - quan@infoplusvn.com
      - chomchomcapital@gmail.com
    on_success: never # default: change
    on_failure: always # default: always



after_success:
  - echo $TRAVIS_BUILD_DIR
  - pwd
  - ls -l
  - ssh -i deploy/104.199.247.193.ppk root@104.199.247.193
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: <shell script/command that runs on deploy>
#    on:
#      branch: master
