language: java

jdk:
  - oraclejdk8

# line 9 resolved an issue where the Travis server would
# try to connect to my remote using ssh-dss, which then caused my
# remote server to puke and demand a password, causing the build
# to time out
dist: trusty
sudo: false

scripts: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


notifications:
  email:
    recipients:
      - quan@infoplusvn.com
      - chomchomcapital@gmail.com
    on_success: never # default: change
    on_failure: always # default: always



after_success:
  on:
    branch: master
  - pwd
  - ls -l

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: <shell script/command that runs on deploy>
#    on:
#      branch: master
