language: java

jdk:
  - openjdk8

branches:
  only:
    - master


install:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test


notifications:
  email:
    recipients:
      - quan@infoplusvn.com
      - chomchomcapital@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

addons:
  ssh_known_hosts: 104.199.247.193
  
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target root@104.199.247.193:/home/java
  on:
    branch: master

after_success:
- echo $TRAVIS_BUILD_DIR
- pwd
- ls -l

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: <shell script/command that runs on deploy>
#    on:
#      branch: master
